/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package russianwordquest;

/**
 *
 * @author Jonathan Galperin <jonathan@galperin.com>
 */
public class NPCDialog extends javax.swing.JDialog {

    private static int npcNumber;
    private static String spell;
    private static String translation;

    /**
     * Creates new form NPCDialog
     */
    public NPCDialog(java.awt.Frame parent, boolean modal, int npcNumber, String spell, String translation) {
        super(parent, modal);
        this.npcNumber = npcNumber;
        this.spell = spell;
        this.translation = translation;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spellTransLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        introLabelSpellTrans = new javax.swing.JLabel();
        introLabelSpell = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        descriptionLabel2 = new javax.swing.JLabel();
        descriptionLabel1 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        spellLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        spellTransLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        spellTransLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spellTransLabel.setText(translation);

        confirmButton.setText("Ok. I've remembered!");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        introLabelSpellTrans.setText("In the glorious mother-tongue (Russian), this means:");

        introLabelSpell.setText("The spell you are learning is: ");

        jLabel3.setText("As a result, you will only see this message once from me.");

        jLabel2.setText("I also teach computer science.");

        jLabel1.setText("However, I am really cruel and like watching people suffer.");

        descriptionLabel2.setText("I will teach you a new spell! Wow. Exciting. ");

        descriptionLabel1.setText("I am here to giude you on your quest. To help with your quest, ");

        titleLabel.setFont(new java.awt.Font("Outage", 0, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Hello There!");

        spellLabel.setText(spell);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(spellLabel)
                .addGap(161, 161, 161))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(159, 159, 159)
                            .addComponent(titleLabel))
                        .addComponent(descriptionLabel1)
                        .addComponent(descriptionLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(introLabelSpell)
                        .addComponent(introLabelSpellTrans)
                        .addComponent(spellTransLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(136, 136, 136)
                            .addComponent(confirmButton)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(spellLabel)
                .addGap(128, 128, 128))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(titleLabel)
                    .addGap(6, 6, 6)
                    .addComponent(descriptionLabel1)
                    .addGap(6, 6, 6)
                    .addComponent(descriptionLabel2)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel1)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel2)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel3)
                    .addGap(16, 16, 16)
                    .addComponent(introLabelSpell)
                    .addGap(6, 6, 6)
                    .addComponent(introLabelSpellTrans)
                    .addGap(6, 6, 6)
                    .addComponent(spellTransLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(6, 6, 6)
                    .addComponent(confirmButton)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        this.dispose();
        System.out.println("reached this statement");
        Runner.start();
    }//GEN-LAST:event_confirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NPCDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NPCDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NPCDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NPCDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NPCDialog dialog = new NPCDialog(new javax.swing.JFrame(), true, npcNumber, spell, translation);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel descriptionLabel1;
    private javax.swing.JLabel descriptionLabel2;
    private javax.swing.JLabel introLabelSpell;
    private javax.swing.JLabel introLabelSpellTrans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel spellLabel;
    private javax.swing.JLabel spellTransLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
